### ISSUE TITLE
dome地址被劫持了

### ISSUE THREAD

**Issue by XDRSZYHRL** [yelog/layui-soul-table#124]
![image](https://user-images.githubusercontent.com/59906163/101709889-4bd5b180-3acb-11eb-9ee0-d9178e949334.png)

**Comment by yelog** [comment]
多谢提醒，已修复

**Comment by XDRSZYHRL** [comment]
你好，请问这个拖动列和拖动行，能单独开启吗？dome中好像是同时开启的。

**Comment by XDRSZYHRL** [comment]
还有我们系统已经使用了Excel1.6，插件里使用的是Excel1.4，会冲突吗？
