### ISSUE TITLE
求助：拖动列和拖动行，能单独开启吗？

### ISSUE THREAD

**Issue by XDRSZYHRL** [yelog/layui-soul-table#125]
你好，我们项目已经使用了Excel1.6，插件里使用的是Excel1.4，使用Excel1.6会冲突吗？

**Comment by yelog** [comment]
可以独立使用的，独立版本为 soulTable.slim.js ，具体可以参考链接的第三点 https://saodiyang.gitee.io/layui-soul-table/#/zh-CN/component/start/install
