### ISSUE TITLE
初始化加载，请求了两次后台。

### ISSUE THREAD

**Issue by hanbingbbs** [yelog/layui-soul-table#14]
![TIM图片20190413164513](https://user-images.githubusercontent.com/24382643/56077282-e9677200-5e0c-11e9-941b-b3ccb81ba04e.png)

**Comment by hanbingbbs** [comment]
刚才跟踪了下代码，明白了，第一次是加载列表，第二次是加载筛选数据。

**Comment by yelog** [comment]
嗯
