### ISSUE TITLE
只实现了到了子层， 孙子层的 data: function(d){  return d.lst } 设置不对吗?  

### ISSUE THREAD

**Issue by fishborne** [yelog/layui-soul-table#15]
yeLog 您好，
测试父子表，表中表，无限层级
发现只能实现一层, 是 孙子层的 data 设置方法不对吗？ 麻烦看下
代码如下:
 function setNewTbl(ele, lst) {
        if (!lst || lst == null || lst.length <= 0) {
            lst = [];
        }
        layui.use(['table', 'soulTable'], function () {
            var table = layui.table;
            var soulTable = layui.soulTable;
            table.render({
                elem: ele
              , height: $(document).height() - $(ele).offset().top - 30
              , data: lst
              , totalRow: true
              , page: false
              , limit: 100000
              , cols: [[ //表头
                  { field: 'hid', title: '种编', width: 120, sort: true, filter: true, }
                , {
                    field: 'hId', title: 'hid', width: 80, show: 1, children: [{
                          title: "大类表"
                        , data: function (d) {
                            console.log(d);
                            return d.lsMidStyleType;
                        }
                        , height: 200
                        , limit: 10000000
                        , page: false
                        , cols: [[
                            {
                                title: '#', width: 60, show: 1, children: [{
                                    title: "小类表"
                                    , data: function (d) {
                                        console.log(d);
                                        return d.lsBaseStyleType;
                                    }
                                    , height: 200
                                    , limit: 10000
                                    , page: false
                                    , cols: [[
                                        { field: 'styleType_Id', title: 'sid', width: 60, sort: true, filter: true },
                                        { field: 'styleType_CName', title: '小类', width: 180, sort: true, filter: true },
                                    ]]
                                }]
                            },
                            { field: 'mId', title: 'midd', width: 100, sort: true, filter: true },
                            { field: 'midStyleTypeName', title: '大类', width: 150, sort: true, filter: true },
                            
                             ]]
                        , done: function () {
                            layui.soulTable.render(this);
                        }
                    }]
                }

                , { field: 'highStyleTypeName', title: '种类', width: 420, sort: true, filter: true,  }
              ]]
              , done: function (res, curr, count) {
                  soulTable.render(this);
              }
            });
            //table.on('tool(packgrn)', function (obj) { 
            //    var data = obj.data; 
            //    var layEvent = obj.event; 
            //    if (layEvent === 'tl-packgrn') 
                    
            //    }
            //});
        });
    }
![image](https://user-images.githubusercontent.com/20026166/56087946-9e9b3800-5ea8-11e9-9f98-91b70a787529.png)

**Comment by fishborne** [comment]
代码截图如下：
![image](https://user-images.githubusercontent.com/20026166/56087967-f76ad080-5ea8-11e9-872c-09d34594979a.png)

**Comment by yelog** [comment]
确实会有问题，已修复，更新代码就会解决问题
