### ISSUE TITLE
如何设置父表行的 children 子表直接展开， 而不是等用户点击再展开

### ISSUE THREAD

**Issue by fishborne** [yelog/layui-soul-table#16]
yelog, 您好
如何设置父表行的 children 子表直接展开 ？
 而不需要等用户点击再展开
尤其在 父表行不多， 直接展开就非常直观

**Comment by yelog** [comment]
设计的时候确实没有考虑到这个情况，我今天晚点扩充一下

**Comment by yelog** [comment]
已更新：子表参数配置 `spread: true`可默认加载。如下
```js
 {title: '#', width: 50, spread: true, children:[])
```
> 慎用，如果主表行数较多，将会大幅度加重浏览器负担

**Comment by fishborne** [comment]
谢谢提醒，一般主子表都只是四五行， 
但是更新并设置后没有效果， 代码如下图
![image](https://user-images.githubusercontent.com/20026166/56145493-f8018500-5fd6-11e9-946f-81f4d686b074.png)

但仍然没有效果（已强制刷新缓存，更改js和css的版本)
![image](https://user-images.githubusercontent.com/20026166/56145737-6c3c2880-5fd7-11e9-8284-c37f4d3da866.png)
