### ISSUE TITLE
soul-table的封装和闭包是用什么写的

### ISSUE THREAD

**Issue by morlie1993** [yelog/layui-soul-table#18]
看了老哥代码 很是羡慕 跪求老哥告知下 设计soul-table的逻辑和思路 以及用到的一些方法 以供学习
谢谢 膜拜

**Comment by yelog** [comment]
模块的封装是按照 layui 官方的模块定义写的 [https://www.layui.com/doc/base/modules.html#extend](https://www.layui.com/doc/base/modules.html#extend)

然后就是jquery的一顿乱操作，没有什么高深的技术，无非就是拼装dom，绑定事件。只不过量稍微大了点

**Comment by morlie1993** [comment]
老哥谦虚的一批 拼装dom的指的是 很多push(<div></div>)对吧 
威武威武 本来我要在table里给合计行的 目前会的就是用jquery的append 无奈定位麻烦 还好老哥的子表完美解决问题
