### ISSUE TITLE
从表如何取主表字段数据当参数请求数据

### ISSUE THREAD

**Issue by jueding920** [yelog/layui-soul-table#2]
从表如何取主表字段数据当参数请求数据？

**Comment by yelog** [comment]
子表参数中加入where参数：
```JavaScript
where：function（d）｛
console.log（d）
return 请求参数
｝
```
这个 d 就是当前行的数据，返回一个json，就是请求参数

手机回复的，自己排版一下

**Comment by gxw2018** [comment]
从表如何取主表字段数据当数据，where可以function，data function 不起作用，我的字段就是一个data类型

**Comment by yelog** [comment]
不好意思，前两天出去玩了，没有及时回复。

**data类型是什么意思，是请求返回一个表格数据数组吗？如果是这样可能不行。**

从表也是一个正常的layui 的 table，要求返回数据是一个符合要求的json，如下
```json
{
    "code": 0,
    "msg": "",
    "data": []
}
```

**Comment by xingrufeng073** [comment]
这个问题原来你解决了啊，没找到文档说明，我还改源码改一身劲自己加了个参数在renderTable函数里拼param.url……

**Comment by yelog** [comment]
@xingrufeng073 都怪当时没把文档写清楚。。。现在已经补充到 README 中了

**Comment by PSKong** [comment]
哦 好吧，，我想错了。那我想要把父表的列中的id传个子表要这样写？
 `
where: {'id': o.id}
`?
