### ISSUE TITLE
点击子表行， 如何获取主表行得obj.data ?

### ISSUE THREAD

**Issue by fishborne** [yelog/layui-soul-table#20]
点击子表行的toolBar， 如何获取主表行得obj.data ? 
如果能获取到主表行的obj data, 那就非常有帮助
谢谢

**Comment by yue916** [comment]
请问点击行获取主表数据的问题解决了吗？我也遇到这个问题了，求分享，谢谢

**Comment by yelog** [comment]
@fishborne 已扩展 tool 事件的第二个参数为 父表当前行数据，详情可参考最新代码示例

@yue916 已给子表扩展 单击行/双击行 事件，第一个参数为子表当前行对象，第二个参数为父表当前行数据

![image](https://user-images.githubusercontent.com/14227866/60086041-f8539480-976c-11e9-9f4b-fc63d731c52c.png)
