### ISSUE TITLE
移动列之后用隐藏显示列问题

### ISSUE THREAD

**Issue by WangXingXing2080** [yelog/layui-soul-table#24]
![move_problem](https://user-images.githubusercontent.com/33862751/56420162-8031a400-62cf-11e9-81a1-e3d6008f7862.png)

现有设定为：当我在哪列上进行筛选操作-表格列进行隐藏列时，选中哪列则不能隐藏哪列
发现问题：
1.移动非锁定列，例：第二列和第三列互换位置
2.当我再次再第二列进行列隐藏操作时，不能隐藏的不是第二列而是第三列

**Comment by yelog** [comment]
不好意思，之前在忙其他的

多谢提醒，问题已修复
