### ISSUE TITLE
使用了子表之后就没有办法监听原生的表头排序了吗？

### ISSUE THREAD

**Issue by yue916** [yelog/layui-soul-table#26]

**Comment by yue916** [comment]
很奇怪，on监听的时候不设置table的elem值才可以成功监听

**Comment by wtwnmp** [comment]
请问您实现了子表的原生表头服务端排序功能吗？思路是什么？

**Comment by yelog** [comment]
加入参数 `sort: 'back'`，就会在请求中加入参数： `field` 和 `order` ，后台自己做排序即可。

>注意：如果后台使用的是我的mybatis插件，引入上面 `sort:'back'` 参数，后台会自动做排序。

**Comment by wtwnmp** [comment]
@yelog 麻烦大佬了！
