### ISSUE TITLE
mybatis 版本号

### ISSUE THREAD

**Issue by PSKong** [yelog/layui-soul-table#3]
请问 你的 mybatis是哪个版本的呢？

**Comment by yelog** [comment]
可在 layui-soul-table-java 项目找到，示例中的 mybatis 版本是 `3.4.6`
[https://github.com/yelog/layui-soul-table-java/blob/master/pom.xml](https://github.com/yelog/layui-soul-table-java/blob/master/pom.xml)

**Comment by PSKong** [comment]
抱歉啊 。。。我又有问题出现了   加了子表之后  table 的 修改和删除无法使用了   
把子表注释之后可以使用

**Comment by PSKong** [comment]
哦~ 我发现了  父子表选中列同步了

**Comment by PSKong** [comment]
请问这个应该怎么解决呢？
