### ISSUE TITLE
一点功能上的细节问题

### ISSUE THREAD

**Issue by colinin** [yelog/layui-soul-table#31]
刚看到这个扩展，我是被子表吸引过来的，bootstraptable不太符合审美，哈哈，大致看了下源码，在拖拽事件最后是否应该加一行$this.removeAttr('style');，毕竟拖拽过程中添加了大量css，如果不移除，有通过css更改过表格样式的话那一列会非常突兀，还有就是如果从后台获取数据，筛选列数据会为空，我再仔细看看吧，前端小白中的小白路过

     
![image](https://user-images.githubusercontent.com/35512826/57663068-fe5e3d80-7624-11e9-9980-f8f75bf8bf5e.png)

**Comment by yelog** [comment]
多谢反馈，如果直接移除style的话，可能会影响使用者自己加上去的样式（自己写的脚本或是第三方插件修改的）。

如果是后台分页的话，表头的筛选数据需要从后台查询，这时就需要后台插件支持。比如已经写好的 java 版的 mybatis 插件： https://github.com/yelog/layui-soul-table-java
