### ISSUE TITLE
列按条件筛选不起作用

### ISSUE THREAD

**Issue by gongel** [yelog/layui-soul-table#32]
[示例](https://github.com/gongel/MCTS/blob/master/log.gif)

**Comment by yelog** [comment]
可否贴一下代码，确定一下是后台筛选，还是前台筛选

**Comment by gongel** [comment]
我的数据是后台，但是筛选不确定
代码链接：https://github.com/gongel/HWdome/blob/3c6329a739618db932b1a7392625f437b8b40ab0/sb/src/main/resources/templates/pattern-detail.html#L161
多谢！

**Comment by yelog** [comment]
看了一下你的代码，是后台分页的，那么表头的筛选就需要后台配合（因为前台数据不全，其他页数据并不在前台）。比如我实现的java版的mybatis 的插件 : https://github.com/yelog/layui-soul-table-java

**Comment by gongel** [comment]
感谢，我回头研究下
