### ISSUE TITLE
前端有很多条数据，选择筛选数据后再取消勾选条件只会显示10条数据是什么情况

### ISSUE THREAD

**Issue by l1120369355** [yelog/layui-soul-table#35]
[
![image](https://user-images.githubusercontent.com/34370351/59338463-fd5c2100-8d34-11e9-870a-0dc6f30d6a50.png)
](url)

[
![image](https://user-images.githubusercontent.com/34370351/59338322-bcfca300-8d34-11e9-9aae-f1b7956a1967.png)
](url)

**Comment by yelog** [comment]
最新的代码已修复此问题

>这个是 layui  table 的历史遗留问题，尽管设置了不分页，但是layui源码中还是会去处理。但是已经通过插件兼容解决了此bug
