### ISSUE TITLE
树形数据如何绑定主子表

### ISSUE THREAD

**Issue by fishborne** [yelog/layui-soul-table#4]
有两个问题需要请教，
1. 树形数据如何绑定主子表?
    目前示例的子表 用的是url 通过where 设置过滤条件来绑定数据， 
   子表的数据可否用 data ?  因为我的子表数据就是主表行数据的一个子集数组

2.  目前设置了列固定 的列， 就没有办法实现soultable的过滤效果， 
    要如何设置才能实现 即能固定列 又有筛选效果？
谢谢

**Comment by yelog** [comment]
很感谢提到了两处问题，由于考虑不周确实有以上描述的问题。

最新代码已经扩展或修复了这两个问题

**更新代码后可以根据下面描述解决问题**

已经引入 `data` 参数， 可为 `Array/Function`，根据你的问题，可使用Function的方式如下：
```js
data: function (d) {
    // d 为当前行数据
    console.log(d)
    return [];
}
```
>`d`为当前行数据，`return` 返回的即为子表数据

**Comment by PSKong** [comment]
请问  如果我想要使用学校作为父表  院系作为子表   那么  父表的参数如何传递给子表呢？

**Comment by PSKong** [comment]
`我是不是需要写一个实体类对date进行封装成`
`{
  "code": 0,
  "msg": "",
  "count": 300,
  "data": [
    {
      "children":{
  "code": 0,
  "msg": "",
  "count": 300,
  "data": [
    {
      "title": "如梦令·黄叶青苔归路",
      "dynasty": "清代",
      "author": "纳兰性德",
      "content": "",
      "type": "写雨,抒情,思念,愁绪",
      "heat": 28,
      "createTime": "2019-03-16 01:35:41"
    },
      "title": "如梦令·黄叶青苔归路",
      "dynasty": "清代",
      "author": "纳兰性德",
      "content": "",
      "type": "写雨,抒情,思念,愁绪",
      "heat": 28,
      "createTime": "2019-03-16 01:35:41"
    },


`这种格式的json串呢

**Comment by PSKong** [comment]
``{ 
“code”：0，
“msg”：“”，
“count”：300，
“data”：[ 
{ 
“children”：{ 
“code”：0，
“msg”：“”，
“count”：300 ，
“数据”：[ 
{ 
“title”：“如梦令·黄叶青苔归路”，
“王朝”：“清代”，
“作者”：“纳兰性德”，
“内容”：“”，
“type”：“写雨，抒情，思念，愁绪”，
“热”：28，
“createTime”：“2019-03-16 01:35:41” 
}，
“title”：“如梦令·黄叶青苔归路“，
”王朝“：”清代“，
”作者“：“纳兰性德”， 
“内容”：“”，
“类型”：“写雨，抒情，思念，愁绪”，
“热”：28，
“创造时间”：“2019-03-16 01:35： 41“ 
}，`

**Comment by PSKong** [comment]
我是否要封装一个实体类形成`{ 
“code”：0，
“msg”：“”，
“count”：300，
“data”：[ 
{ 
“children”：{ 
“code”：0，
“msg”：“”，
“count”：300 ，
“数据”：[ 
{ 
“title”：“如梦令·黄叶青苔归路”，
“王朝”：“清代”，
“作者”：“纳兰性德”，
“内容”：“”，
“type”：“写雨，抒情，思念，愁绪”，
“热”：28，
“createTime”：“2019-03-16 01:35:41” 
}，
“title”：“如梦令·黄叶青苔归路“，
”王朝“：”清代“，
”作者“：“纳兰性德”， 
“内容”：“”，
“类型”：“写雨，抒情，思念，愁绪”，
“热”：28，
“创造时间”：“2019-03-16 01:35： 41“ 
}，`这样的json串？

**Comment by PSKong** [comment]
父子表的json串是否可以为
`{
  "code": 0,
  "msg": "",
  "count": 300,
  "data": [
    {
       "children":{
  "code": 0,
  "msg": "",
  "count": 300,
  "data": [
    {
      "title": "如梦令·黄叶青苔归路",
      "dynasty": "清代",
      "author": "纳兰性德",
      "content": "黄叶青苔归路，屧粉衣香何处。消息竟沉沉，今夜相思几许。秋雨，秋雨，一半因风吹去。(版本一)木叶纷纷归路，残月晓风何处。消息竟沉沉，今夜相思几许。秋雨，秋雨，一半因风吹去。(版本二)",
      "type": "写雨,抒情,思念,愁绪",
      "heat": 28,
      "createTime": "2019-03-16 01:35:41"
    }},
      "title": "如梦令·黄叶青苔归路",
      "dynasty": "清代",
      "author": "纳兰性德",
      "content": "黄叶青苔归路，屧粉衣香何处。消息竟沉沉，今夜相思几许。秋雨，秋雨，一半因风吹去。(版本一)木叶纷纷归路，残月晓风何处。消息竟沉沉，今夜相思几许。秋雨，秋雨，一半因风吹去。(版本二)",
      "type": "写雨,抒情,思念,愁绪",
      "heat": 28,
      "createTime": "2019-03-16 01:35:41"
    }}`

**Comment by yelog** [comment]
@PSKong 不是这样用的，如果你想子表和父表分开请求，子表的 `url` 为请求子表数据的请求，`where` 为请求参数。
参考： [https://github.com/yelog/layui-soul-table/issues/2](https://github.com/yelog/layui-soul-table/issues/2)

**Comment by fishborne** [comment]
@yelog 谢谢作者的快速回复和行动
子表虽然还没有测试， 但解决思路已经清晰明了
谢谢
