### ISSUE TITLE
【需求】新增一个tips

### ISSUE THREAD

**Issue by GitHubAsural** [yelog/layui-soul-table#43]
<img width="385" alt="1" src="https://user-images.githubusercontent.com/21130973/62271749-f798d700-b46b-11e9-9119-32b479f27379.png">
<img width="173" alt="2" src="https://user-images.githubusercontent.com/21130973/62271757-fbc4f480-b46b-11e9-8d49-df3a207ca913.png">
如图：文本超出列宽时，鼠标移动上去不点击显示tips【内容】 点击时正常显示

**Comment by yelog** [comment]
感觉体验不会很好

**Comment by yelog** [comment]
已实现 [内容超出设置](https://saodiyang.gitee.io/layui-soul-table/#/zh-CN/component/basic/overflow)
