### ISSUE TITLE
为啥我的合并列还是有问题

### ISSUE THREAD

**Issue by devcyx** [yelog/layui-soul-table#46]
>如图
![image](https://user-images.githubusercontent.com/38395095/65103788-e303a480-da01-11e9-80b7-1f094a556685.png)

**Comment by yelog** [comment]
检查一下 `tableMerge.js` 是否为最新代码（在ext目录下），如果不是请先更新。

如果还存在问题，请贴出 `table.render` 完整代码，最好附上 `layui版本`、`浏览器信息`

**Comment by devcyx** [comment]
刚所有的都更新了，还是一样的问题
layui 2.5.5
浏览器chrome
table.render:
![image](https://user-images.githubusercontent.com/38395095/65104946-d1bc9700-da05-11e9-8831-614e4b0988e6.png)
