### ISSUE TITLE
懒加载

### ISSUE THREAD

**Issue by githubreer** [yelog/layui-soul-table#51]
懒加载子表怎么设置动态参数？

**Comment by yelog** [comment]
什么参数？请求参数吗？where条件传入方法即可：[子表数据来源](https://saodiyang.gitee.io/layui-soul-table/#/zh-CN/component/child/request)

**Comment by githubreer** [comment]
where 里面填写变量参数没起作用 where:{type:1,capter_id:capter_id}  一直是默认值，修改变量值没用

**Comment by githubreer** [comment]
找到了，用函数带动态数据、打扰了..

**Comment by yelog** [comment]
嗯，没问题的话，就关了这个ISSUE吧
