### ISSUE TITLE
在首次加载时，table获取不了当前实例

### ISSUE THREAD

**Issue by 15203589368** [yelog/layui-soul-table#56]
在外面reload就有实例，在soultable里面首次加载，就找不到c.config={}
![7DU%11)3~CSGGH`7 H_Z@XS](https://user-images.githubusercontent.com/31119494/68007315-2f572b00-fcb6-11e9-8358-fe17628fa2c6.png)

**Comment by yelog** [comment]
c.config 是什么？报错吗？
