### ISSUE TITLE
页面有一个表格应用了soulTable后， 其他没有应用的table 右下角都会出现 "编辑筛选条件" 的按钮

### ISSUE THREAD

**Issue by fishborne** [yelog/layui-soul-table#6]
一个页面有多个table, 
其中一个表格应用了soulTable后， 
其他没有应用 soultable 的table 右下角都会出现 "编辑筛选条件" 的按钮?
点击会弹框， 无法添加条件，
是我哪里设置不对吗？ 应该如何处理

**Comment by yelog** [comment]
没有复现的你描述的问题，可以把代码贴出来，会节省很多时间
