### ISSUE TITLE
启用列记忆后合计列错误，ajax会有2次ajax数据请求

### ISSUE THREAD

**Issue by gongzhw** [yelog/layui-soul-table#71]
1.开启列记忆后， table 设置totalRow: true,列也设置了totalRow: true,  合计列会报错，模版列中的js func都执行失败，比如列中，有 xx.toFixed(2)这样都报错了，感觉对模版列不支持啊
2.开启后列记忆后，每次ajax请求2次数据接口

列代码
 {
                                field: 'realTotalPrice',
                                title: '应收总额', totalRow: true,
                                sort: true,
                                templet: function(d) {
                                    return '<span>' +d.realTotalPrice.toFixed(2) +
                                        '</span>';
                                }
                            },

**Comment by gongzhw** [comment]
能否把列记忆、拖拽、位置，单独出一个插件？好多人用不到复杂的筛选，三克油

**Comment by yelog** [comment]
已经独立出来了 soultable.slim.js 
[https://saodiyang.gitee.io/layui-soul-table/#/zh-CN/component/start/install#1.-soultable-du-li-shi-yong](https://saodiyang.gitee.io/layui-soul-table/#/zh-CN/component/start/install#1.-soultable-du-li-shi-yong)
