### ISSUE TITLE
可以动态多层子表么

### ISSUE THREAD

**Issue by 610232785** [yelog/layui-soul-table#79]
比如在部门中使用soultable，部门层次可以无限加深，不能在页面上写满多层子表，请问可以实现动态多层次子表么

**Comment by yelog** [comment]
可以啊 https://saodiyang.gitee.io/layui-soul-table/#/zh-CN/component/child/deep

**Comment by 610232785** [comment]
可能我描述的不清晰，你提供的文档是事先固定了多层，不能动态拓展多层。
比如有需求如下：
工程的菜单可以自定义拓展多层级，按照这个需求就不能固定在页面上写死了三层或者四层，当工程菜单有5层级的时候就数据显示不全了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"杨玉杰（Chris Yang）"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月13日(星期三) 下午5:26
收件人:&nbsp;"yelog/layui-soul-table"<layui-soul-table@noreply.github.com&gt;;
抄送:&nbsp;"林锦权"<610232785@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [yelog/layui-soul-table] 可以动态多层子表么 (#79)





 
可以啊 https://saodiyang.gitee.io/layui-soul-table/#/zh-CN/component/child/deep

**Comment by yelog** [comment]
不定深度的子表可以尝试通过动态构建子表（children: funcition） 

https://saodiyang.gitee.io/layui-soul-table/#/zh-CN/component/child/basic
