### ISSUE TITLE
当设置锁定列后，拖动非锁定列到锁定列位置，出现错位

### ISSUE THREAD

**Issue by WangXingXing2080** [yelog/layui-soul-table#9]
当设置锁定列后，拖动非锁定列到锁定列位置，出现错位。
查看页面代码，对锁定列的遮罩层进行隐藏，发现锁定列被遮罩部分发生移动

**Comment by PSKong** [comment]
双击表头可以刷新的兄弟

**Comment by WangXingXing2080** [comment]
双击表头刷新什么？ 已经错位了 不移动 回不来

**Comment by PSKong** [comment]
你那边双击表头不能恢复原来布局吗？

**Comment by yelog** [comment]
@WangXingXing2080 确实存在这个问题。稍后我会修复一下，禁止锁定列移动

**Comment by WangXingXing2080** [comment]
好的 谢谢 等待你的更新@yelog

**Comment by yelog** [comment]
@WangXingXing2080 已更新修复了此问题
