### ISSUE TITLE
后台分页的情况下，先筛选某数据，然后修改每页记录数，再点击某一列排序，每页记录数恢复之前的状态

### ISSUE THREAD

**Issue by xasunjing** [yelog/layui-soul-table#91]
在线demo中可复现
在后台分页的demo中，先筛选某一列的数据
![1](https://user-images.githubusercontent.com/41457165/82644895-a0573380-9c44-11ea-8995-f34275fe9d33.png)
然后修改每页记录数为40
![2](https://user-images.githubusercontent.com/41457165/82644914-a9e09b80-9c44-11ea-87d4-757ca8c9af07.png)
然后排序某列，每页记录数恢复为之前的20条
![3](https://user-images.githubusercontent.com/41457165/82644947-b49b3080-9c44-11ea-825d-f6aee706ae18.png)
经过尝试，貌似会记录第一次筛选时的每页记录数，后面无论时筛选还是排序，都会恢复到当时的数值

**Comment by yelog** [comment]
已修复

**Comment by xasunjing** [comment]
感谢作者快速修复，这个插件真的很棒
