### ISSUE TITLE
使用复杂表头的导出excel中存在的bug

### ISSUE THREAD

**Issue by yeyingwuyue** [yelog/layui-soul-table#95]
tableFilter.js 中 line 2635: " j = j + cols[i][j].colspan - 1"，当cols[i][j].colspan 获取到的值时字符串时，会导致 j 的值和预期不一致:我遇到的情况是，本该循环两次的 ( cols[i][j].colspan = 2), 但是在第一次循环中 获取到的 cols[i][j].colspan = “2”， 这就导致执行 line2635 这条语句时 j 的赋值超出的预期，没有进行下一次的循环，进而导致后续的导出excel操作中报错。
面向我自己的需求，将这条修改为  j = j + parseInt(cols[i][j].colspan) - 1, 得以实现预期循环。

**Comment by yelog** [comment]
多谢提醒，已修复
